name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17 # Using PostgreSQL 17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Node.js 20 to meet package requirements

      - name: Add PostgreSQL repository
        run: |
          # Download the PostgreSQL GPG key
          wget --quiet -O- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg

          # Add the PostgreSQL repository to the sources list
          echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null

          # Update the package list
          sudo apt-get update

      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client-17

      - name: Set up database
        env:
          PGPASSWORD: postgres # Provide the password for the "postgres" user
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'test_db'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE test_db;"

      - name: Copy .env.ci to .env
        run: cp .env.ci .env

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: npm test

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format:check
