name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17 # Updated to PostgreSQL 17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Node.js 20 to meet package requirements

      - name: Install dependencies
        run: npm install

      - name: Set up database
        env:
          PGPASSWORD: postgres # Provide the password for the "postgres" user
        run: |
          sudo apt-get install postgresql-client-17  # Install PostgreSQL 17 client
          psql -h localhost -U postgres -c "CREATE DATABASE test_db;"

      - name: Copy .env.ci to .env
        run: cp .env.ci .env

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: npm test

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format:check
